# Generated by Django 6.0.4 on 2026-04-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codice_fiscale', models.CharField(db_column='Codice_fiscale', max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('cognome', models.CharField(db_column='Cognome', max_length=100)),
                ('data_nascita', models.DateField(db_column='Data_nascita')),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data_inizio', models.DateField(db_column='Data_inizio')),
                ('data_fine', models.DateField(db_column='Data_fine')),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('prezzo', models.DecimalField(db_column='Prezzo', decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'Itinerario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Merce',
            fields=[
                ('sscc', models.CharField(db_column='SSCC', max_length=18, primary_key=True, serialize=False)),
                ('peso', models.FloatField(db_column='Peso')),
                ('paese', models.CharField(db_column='Paese', max_length=50)),
                ('genere', models.CharField(db_column='Genere', max_length=100)),
                ('id_container', models.CharField(blank=True, db_column='ID_container', max_length=11, null=True)),
            ],
            options={
                'db_table': 'Merce',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Banchina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_column='Numero')),
                ('settore', models.IntegerField(db_column='Settore')),
                ('tipo', models.CharField(db_column='Tipo', max_length=8)),
                ('lunghezza', models.FloatField(db_column='Lunghezza')),
            ],
            options={
                'db_table': 'Banchina',
                'managed': True,
                'unique_together': {('numero', 'settore')},
            },
        ),
        migrations.CreateModel(
            name='Guida',
            fields=[
                ('codice_fiscale', models.CharField(db_column='Codice_fiscale', max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('cognome', models.CharField(db_column='Cognome', max_length=100)),
                ('data_nascita', models.DateField(db_column='Data_nascita')),
                ('numero_licensa', models.IntegerField(db_column='Numero_licensa', unique=True)),
                ('stipendio', models.DecimalField(db_column='Stipendio', decimal_places=2, max_digits=20)),
                ('data_assunzione', models.DateField(db_column='Data_assunzione')),
                ('valutazione', models.FloatField(db_column='Valutazione')),
                ('id_itinerario', models.ForeignKey(blank=True, db_column='ID_itinerario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.itinerario')),
            ],
            options={
                'db_table': 'Guida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('localita', models.CharField(db_column='Localita', max_length=100)),
                ('tipo', models.CharField(db_column='Tipo', max_length=100)),
                ('capacita', models.FloatField(db_column='Capacita')),
            ],
            options={
                'db_table': 'Magazzino',
                'managed': True,
                'unique_together': {('nome', 'localita')},
            },
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('imo', models.CharField(db_column='IMO', max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('nazionalita', models.CharField(db_column='Nazionalita', max_length=100)),
                ('compagnia', models.CharField(db_column='Compagnia', max_length=100)),
                ('altezza', models.FloatField(db_column='Altezza')),
                ('lunghezza', models.FloatField(db_column='Lunghezza')),
                ('larghezza', models.FloatField(db_column='Larghezza')),
                ('peso_massimo', models.FloatField(blank=True, db_column='Peso_massimo', null=True)),
                ('capacita', models.IntegerField(blank=True, db_column='Capacita', null=True)),
                ('peso_occupato', models.FloatField(blank=True, db_column='Peso_occupato', null=True)),
                ('volume_occupato', models.IntegerField(blank=True, db_column='Volume_occupato', null=True)),
                ('capienza', models.IntegerField(blank=True, db_column='Capienza', null=True)),
                ('tipo', models.CharField(db_column='Tipo', max_length=8)),
                ('id_itinerario', models.ForeignKey(blank=True, db_column='ID_itinerario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.itinerario')),
                ('numero_banchina', models.ForeignKey(blank=True, db_column='Numero_banchina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.banchina')),
                ('settore_banchina', models.ForeignKey(blank=True, db_column='Settore_banchina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nave_settore_banchina_set', to='core.banchina')),
            ],
            options={
                'db_table': 'Nave',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=11, primary_key=True, serialize=False)),
                ('dimensione', models.IntegerField(db_column='Dimensione')),
                ('peso', models.FloatField(db_column='Peso')),
                ('marchio', models.CharField(db_column='Marchio', max_length=100)),
                ('imo', models.ForeignKey(blank=True, db_column='IMO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.nave')),
            ],
            options={
                'db_table': 'Container',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_column='Numero')),
                ('classe', models.CharField(db_column='Classe', max_length=7)),
                ('tipo', models.CharField(db_column='Tipo', max_length=12)),
                ('imo', models.ForeignKey(db_column='IMO', on_delete=django.db.models.deletion.DO_NOTHING, to='core.nave')),
            ],
            options={
                'db_table': 'Stanza',
                'managed': True,
                'unique_together': {('imo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data_inizio', models.DateField(db_column='Data_inizio')),
                ('scadenza', models.DateField(db_column='Scadenza')),
                ('servizio_guida', models.IntegerField(db_column='Servizio_guida')),
                ('codice_fiscale', models.ForeignKey(db_column='Codice_fiscale', on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('imo', models.ForeignKey(db_column='IMO', on_delete=django.db.models.deletion.DO_NOTHING, to='core.stanza')),
                ('numero', models.ForeignKey(db_column='Numero', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prenotazione_numero_set', to='core.stanza')),
            ],
            options={
                'db_table': 'Prenotazione',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LingueGuida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(db_column='Lingua', max_length=50)),
                ('livello', models.CharField(db_column='Livello', max_length=6)),
                ('codice_fiscale', models.ForeignKey(db_column='Codice_fiscale', on_delete=django.db.models.deletion.DO_NOTHING, to='core.guida')),
            ],
            options={
                'db_table': 'Lingue_guida',
                'managed': True,
                'unique_together': {('codice_fiscale', 'lingua')},
            },
        ),
        migrations.CreateModel(
            name='Stoccaggio',
            fields=[
                ('sscc', models.OneToOneField(db_column='SSCC', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.merce')),
                ('localita_magazzino', models.ForeignKey(db_column='Localita_magazzino', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stoccaggio_localita_magazzino_set', to='core.magazzino')),
                ('nome_magazzino', models.ForeignKey(db_column='Nome_magazzino', on_delete=django.db.models.deletion.DO_NOTHING, to='core.magazzino')),
            ],
            options={
                'db_table': 'Stoccaggio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TappeItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tappa', models.CharField(db_column='Tappa', max_length=100)),
                ('id_itinerario', models.ForeignKey(db_column='ID_itinerario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.itinerario')),
            ],
            options={
                'db_table': 'Tappe_itinerario',
                'managed': True,
                'unique_together': {('id_itinerario', 'tappa')},
            },
        ),
    ]
