# Generated by Django 6.0.4 on 2026-05-02 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usercliente_usernave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banchina',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lingueguida',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='magazzino',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stanza',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tappeitinerario',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='UserBanchina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_banchina', models.IntegerField(default=0)),
                ('settore_banchina', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_userbanchina',
                'unique_together': {('user', 'numero_banchina', 'settore_banchina')},
            },
        ),
        migrations.CreateModel(
            name='UserMagazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_magazzino', models.CharField(default='Magazzino', max_length=100)),
                ('localita_magazzino', models.CharField(default='Localita', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_usermagazzino',
                'unique_together': {('user', 'nome_magazzino', 'localita_magazzino')},
            },
        ),
    ]
