# Generated by Django 6.0.4 on 2026-05-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_banchina_options_alter_lingueguida_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nave',
            options={'managed': False},
        ),
    ]
