# Generated by Django 6.0.4 on 2026-05-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nave_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merce',
            options={'managed': False},
        ),
    ]
