# Generated by Django 6.0.4 on 2026-05-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_merce_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stoccaggio',
            options={'managed': False},
        ),
    ]
