# Generated by Django 6.0.4 on 2026-05-07 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_stoccaggio_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_userguida',
                'unique_together': {('user', 'guida')},
            },
        ),
        migrations.CreateModel(
            name='UserItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itinerario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_useritinerario',
                'unique_together': {('user', 'itinerario')},
            },
        ),
    ]
