# Generated by Django 6.0.4 on 2026-05-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userguida_useritinerario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'managed': False},
        ),
    ]
